version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: >-
      sh -c "python manage.py migrate
      && python manage.py collectstatic --noinput
      && gunicorn euskodev.wsgi:application --bind 0.0.0.0:8000"
    environment:
      DJANGO_SETTINGS_MODULE: euskodev.settings
    ports:
      - "8000:8000"
    volumes:
      - static_data:/euskodev/static
      - media_data:/euskodev/media
      - sqlite_data:/euskodev/db
    restart: always

volumes:
  static_data:
  media_data:
  sqlite_data:
