# Generated by Django 5.0.7 on 2025-04-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre de la empresa')),
                ('legal_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Razón social')),
                ('vat_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='CIF/NIF')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de contacto')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Sitio web')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código postal')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='País')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='companies/logos/', verbose_name='Logo de la empresa')),
                ('latitude', models.CharField(blank=True, max_length=30, null=True, verbose_name='Latitud')),
                ('longitude', models.CharField(blank=True, max_length=30, null=True, verbose_name='Longitud')),
                ('has_website', models.BooleanField(blank=True, default=None, null=True, verbose_name='¿Tiene página web?')),
                ('has_mobile_app', models.BooleanField(blank=True, default=None, null=True, verbose_name='¿Tiene app móvil?')),
                ('has_custom_software', models.BooleanField(blank=True, default=None, null=True, verbose_name='¿Usa software propio?')),
                ('uses_ai', models.BooleanField(blank=True, default=None, null=True, verbose_name='¿Utiliza inteligencia artificial?')),
                ('is_competition_company', models.BooleanField(blank=True, default=None, null=True, verbose_name='¿Es competencia de Euskdoev?')),
                ('manager_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre del gerente')),
                ('manager_phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono del gerente')),
                ('manager_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email del gerente')),
                ('visited', models.BooleanField(default=False, verbose_name='¿Ha sido visitada?')),
                ('visit_date', models.DateField(blank=True, null=True, verbose_name='Fecha de visita')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comentarios')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Activa?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['name'],
            },
        ),
    ]
