# Generated by Django 5.0.7 on 2026-03-09 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalizationAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Nombre de la empresa')),
                ('contact_name', models.CharField(max_length=255, verbose_name='Nombre de contacto')),
                ('company_email', models.EmailField(max_length=254, verbose_name='Correo electrónico de contacto')),
                ('contact_tel', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono de contacto (opcional)')),
                ('business_activity', models.CharField(blank=True, max_length=300, null=True, verbose_name='¿A qué se dedica la empresa?')),
                ('has_website', models.BooleanField(blank=True, choices=[(True, 'Sí'), (False, 'No'), (None, 'No lo sé')], default=None, null=True, verbose_name='La empresa tiene una página web corporativa')),
                ('website_responsive', models.BooleanField(blank=True, choices=[(True, 'Sí'), (False, 'No'), (None, 'No lo sé')], default=None, null=True, verbose_name='La web es responsive y se adapta a móviles')),
                ('seo_optimized', models.BooleanField(blank=True, choices=[(True, 'Sí'), (False, 'No'), (None, 'No lo sé')], default=None, null=True, verbose_name='La web está optimizada para buscadores (SEO)')),
                ('has_google_business', models.BooleanField(blank=True, choices=[(True, 'Sí'), (False, 'No'), (None, 'No lo sé')], default=None, null=True, verbose_name='La empresa tiene ficha en Google Business')),
                ('uses_analytics', models.BooleanField(blank=True, choices=[(True, 'Sí'), (False, 'No'), (None, 'No lo sé')], default=None, null=True, verbose_name='Utiliza herramientas como Google Analytics')),
                ('active_social_media', models.BooleanField(blank=True, choices=[(True, 'Sí'), (False, 'No'), (None, 'No lo sé')], default=None, null=True, verbose_name='Tiene presencia activa en redes sociales')),
                ('does_ads', models.BooleanField(blank=True, choices=[(True, 'Sí'), (False, 'No'), (None, 'No lo sé')], default=None, null=True, verbose_name='Hace campañas en redes o Google Ads')),
                ('uses_newsletters', models.BooleanField(blank=True, choices=[(True, 'Sí'), (False, 'No'), (None, 'No lo sé')], default=None, null=True, verbose_name='Envía newsletters o emails promocionales')),
                ('uses_crm', models.BooleanField(blank=True, choices=[(True, 'Sí'), (False, 'No'), (None, 'No lo sé')], default=None, null=True, verbose_name='Utiliza un CRM para gestión de contactos/clientes')),
                ('has_lead_campaigns', models.BooleanField(blank=True, choices=[(True, 'Sí'), (False, 'No'), (None, 'No lo sé')], default=None, null=True, verbose_name='Realiza campañas de captación de leads')),
                ('sells_online', models.BooleanField(blank=True, choices=[(True, 'Sí'), (False, 'No'), (None, 'No lo sé')], default=None, null=True, verbose_name='Vende productos o servicios online')),
                ('accepts_online_payments', models.BooleanField(blank=True, choices=[(True, 'Sí'), (False, 'No'), (None, 'No lo sé')], default=None, null=True, verbose_name='Acepta pagos digitales')),
                ('has_booking_system', models.BooleanField(blank=True, choices=[(True, 'Sí'), (False, 'No'), (None, 'No lo sé')], default=None, null=True, verbose_name='Tiene un sistema de reservas online')),
                ('has_cart_system', models.BooleanField(blank=True, choices=[(True, 'Sí'), (False, 'No'), (None, 'No lo sé')], default=None, null=True, verbose_name='Tiene carrito de compras en su web')),
                ('uses_erp', models.BooleanField(blank=True, choices=[(True, 'Sí'), (False, 'No'), (None, 'No lo sé')], default=None, null=True, verbose_name='Utiliza un ERP para la gestión interna')),
                ('uses_digital_invoicing', models.BooleanField(blank=True, choices=[(True, 'Sí'), (False, 'No'), (None, 'No lo sé')], default=None, null=True, verbose_name='Usa facturación digital')),
                ('automates_processes', models.BooleanField(blank=True, choices=[(True, 'Sí'), (False, 'No'), (None, 'No lo sé')], default=None, null=True, verbose_name='Automatiza procesos repetitivos')),
                ('uses_collab_software', models.BooleanField(blank=True, choices=[(True, 'Sí'), (False, 'No'), (None, 'No lo sé')], default=None, null=True, verbose_name='Utiliza software colaborativo')),
                ('has_backup_system', models.BooleanField(blank=True, choices=[(True, 'Sí'), (False, 'No'), (None, 'No lo sé')], default=None, null=True, verbose_name='Tiene copias de seguridad automatizadas')),
                ('has_chatbot', models.BooleanField(blank=True, choices=[(True, 'Sí'), (False, 'No'), (None, 'No lo sé')], default=None, null=True, verbose_name='Tiene un chatbot o asistente virtual')),
                ('uses_whatsapp', models.BooleanField(blank=True, choices=[(True, 'Sí'), (False, 'No'), (None, 'No lo sé')], default=None, null=True, verbose_name='Utiliza WhatsApp Business u otro canal directo')),
                ('has_support_system', models.BooleanField(blank=True, choices=[(True, 'Sí'), (False, 'No'), (None, 'No lo sé')], default=None, null=True, verbose_name='Tiene sistema de soporte o tickets')),
                ('quick_response_channels', models.BooleanField(blank=True, choices=[(True, 'Sí'), (False, 'No'), (None, 'No lo sé')], default=None, null=True, verbose_name='Responde rápidamente en canales digitales')),
                ('has_mobile_app', models.BooleanField(blank=True, choices=[(True, 'Sí'), (False, 'No'), (None, 'No lo sé')], default=None, null=True, verbose_name='Tiene una app móvil propia')),
                ('has_private_area', models.BooleanField(blank=True, choices=[(True, 'Sí'), (False, 'No'), (None, 'No lo sé')], default=None, null=True, verbose_name='Tiene una zona privada o funcionalidades especiales')),
                ('employees_mobile_access', models.BooleanField(blank=True, choices=[(True, 'Sí'), (False, 'No'), (None, 'No lo sé')], default=None, null=True, verbose_name='Los empleados pueden trabajar desde el móvil')),
                ('uses_productivity_apps', models.BooleanField(blank=True, choices=[(True, 'Sí'), (False, 'No'), (None, 'No lo sé')], default=None, null=True, verbose_name='Utiliza apps móviles de productividad')),
                ('analyzes_metrics', models.BooleanField(blank=True, choices=[(True, 'Sí'), (False, 'No'), (None, 'No lo sé')], default=None, null=True, verbose_name='Analiza métricas de ventas y clientes')),
                ('uses_dashboards', models.BooleanField(blank=True, choices=[(True, 'Sí'), (False, 'No'), (None, 'No lo sé')], default=None, null=True, verbose_name='Utiliza dashboards para decisiones')),
                ('tracks_kpis', models.BooleanField(blank=True, choices=[(True, 'Sí'), (False, 'No'), (None, 'No lo sé')], default=None, null=True, verbose_name='Mide objetivos digitales (KPI)')),
                ('has_ssl', models.BooleanField(blank=True, choices=[(True, 'Sí'), (False, 'No'), (None, 'No lo sé')], default=None, null=True, verbose_name='Su web tiene certificado SSL')),
                ('secure_passwords', models.BooleanField(blank=True, choices=[(True, 'Sí'), (False, 'No'), (None, 'No lo sé')], default=None, null=True, verbose_name='Usa contraseñas seguras y doble factor')),
                ('gdpr_compliant', models.BooleanField(blank=True, choices=[(True, 'Sí'), (False, 'No'), (None, 'No lo sé')], default=None, null=True, verbose_name='Está adaptado a la normativa RGPD')),
                ('performs_security_audits', models.BooleanField(blank=True, choices=[(True, 'Sí'), (False, 'No'), (None, 'No lo sé')], default=None, null=True, verbose_name='Realiza auditorías de seguridad')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de envío')),
            ],
        ),
    ]
