# Generated by Django 5.0.6 on 2024-07-11 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_cuerpo_blog_cuerpoe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='cuerpoe',
            new_name='cuerpo',
        ),
    ]
