# Generated by Django 5.0.6 on 2024-07-12 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_cuerpoe_blog_cuerpo'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='resumen',
            field=models.TextField(blank=True, null=True),
        ),
    ]
