# Generated by Django 5.0.7 on 2026-06-19 00:04

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_blog_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='resumen_es',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='resumen_eu',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='titulo_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='titulo_eu',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
