# Generated by Django 5.0.7 on 2025-04-17 12:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Primer nombre')),
                ('second_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Segundo nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Primer apellido')),
                ('second_last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Segundo apellido')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono principal')),
                ('secondary_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono secundario')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='Puesto de trabajo')),
                ('address', models.CharField(blank=True, max_length=300, null=True, verbose_name='Dirección')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='País')),
                ('nif', models.CharField(blank=True, max_length=50, null=True, verbose_name='NIF/CIF')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=10, null=True, verbose_name='Género')),
                ('nationality', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nacionalidad')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de alta')),
                ('manager_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre del gerente')),
                ('manager_phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono del gerente')),
                ('manager_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email del gerente')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.company')),
            ],
        ),
    ]
