# Generated by Django 5.0.6 on 2024-07-11 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_blog_cuerpo_alter_blog_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='cuerpo',
            new_name='cuerpoe',
        ),
    ]
