# Generated by Django 5.0.7 on 2025-11-24 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_budget_numero_presupuesto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='numero_presupuesto',
        ),
        migrations.AddField(
            model_name='budget',
            name='numero_presupuesto_manual',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de presupuesto (opcional y editable)'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='impuesto_porcentaje',
            field=models.DecimalField(blank=True, decimal_places=2, default=21.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='cantidad',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='precio_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
