# Generated by Django 5.0.7 on 2025-11-24 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_budget_fecha_vencimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='numero_presupuesto_manual',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de presupuesto (editable)'),
        ),
    ]
