version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/euskodev
      - static_volume:/euskodev/staticfiles
      - media_volume:/euskodev/media
    expose:
      - "8000"
    env_file:
      - .env
    command: gunicorn euskodev.wsgi:application --bind 0.0.0.0:8000

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/euskodev/staticfiles
      - media_volume:/euskodev/media
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  static_volume:
  media_volume:
