# Generated by Django 5.0.7 on 2025-11-24 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0006_alter_budget_numero_presupuesto_manual'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Olvin Duarte', max_length=100)),
                ('nombre_comercial', models.CharField(default='Euskodev', max_length=100)),
                ('nif', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion_fiscal', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('web', models.URLField(blank=True, null=True)),
                ('cuenta_bancaria', models.CharField(blank=True, max_length=50, null=True)),
                ('banco', models.CharField(blank=True, max_length=100, null=True)),
                ('forma_pago', models.CharField(default='Transferencia bancaria', max_length=50)),
                ('mostrar_datos_pago_en_presupuesto', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='budget',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.companyinfo'),
        ),
    ]
