# Generated by Django 5.0.7 on 2025-11-24 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0007_companyinfo_budget_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='banco',
            field=models.CharField(blank=True, choices=[('CAIXABANK', 'CaixaBank'), ('SANTANDER', 'Banco Santander'), ('BBVA', 'BBVA'), ('SABADELL', 'Banco Sabadell'), ('ING', 'ING España'), ('BANKINTER', 'Bankinter'), ('OPENBANK', 'OpenBank'), ('EVOBANK', 'EVO Banco'), ('ABANCA', 'ABANCA'), ('OTRO', 'Otro / Personalizado')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='forma_pago',
            field=models.CharField(choices=[('TRANSFERENCIA', 'Transferencia bancaria'), ('BIZUM', 'Bizum'), ('PAYPAL', 'PayPal'), ('TPV', 'TPV Virtual (Tarjeta)'), ('STRIPE', 'Stripe (Tarjeta / Apple Pay / Google Pay)')], default='TRANSFERENCIA', max_length=50),
        ),
    ]
