# Generated by Django 5.0.7 on 2026-03-20 12:11

import applications.home.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_blog_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='media/img', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), applications.home.models.validate_image_size]),
        ),
    ]
