# Generated by Django 5.0.7 on 2025-11-24 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_remove_budget_numero_presupuesto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
